storage:
  type: MySQL
  host: localhost
  port: 3306
  ssl: false
  database: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASS}

cosmetics:
  firework:
    enabled: true
    allowed-firework-models:
      BALL: 5000
      BURST: 5000
      STAR: 5000
      CREEPER: 5000
      BALL_LARGE: 5000