storage:
  type: MySQL
  host: localhost
  port: 3306
  ssl: false
  database: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASS}

broadcast-new-best-time-all-players: true

allow-block-interaction-on-lobby:
  place-block: false
  break-block: true

deny-block-placement-on:
  - "BARRIER"

void-detection:
  detection-height: 10
  detect-on:
    lobby: true
    spectating: true

blocked-commands:
  - "spawn"

cheat-protection:
  kick-if-failed-min-blocks-req: true
  kick-if-failed-min-time: false
  kick-if-reached-to-end-without-starting: true

cosmetics:
  firework:
    enabled: true
    allowed-firework-models:
      BALL: 5000
      BURST: 5000
      STAR: 5000
      CREEPER: 5000
      BALL_LARGE: 5000
  material:
    default: "STONE"
    allowed-materials:
      STAINED_GLASS_PANE: 2600
      WOOL: 6500
      GOLD_BLOCK: 4500
