storage:
  type: MySQL
  host: localhost
  port: 3306
  ssl: false
  database: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASS}

broadcast-new-best-time-all-players: true

##Action bar is run on a separate thread!
update-action-bar-on-every-ms: 500

allow-block-interaction-on-lobby:
  place-block: false
  break-block: true

deny-block-placement-on:
  - "BARRIER"

void-detection:
  detection-height: 10
  detect-on:
    lobby: true
    spectating: true

blocked-commands:
  - "spawn"

cheat-protection:
  kick-if-failed-min-blocks-req: true
  kick-if-failed-min-time: false
  kick-if-reached-to-end-without-starting: true

lobby-items:
  shop:
    enabled: true
    item: "[BASE64]:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjIxNjQ2MzU5MzM0OTZhZmNkNWQ3OTNhZThiNTNjYWI4NjI0N2YwN2U4NjI0YzQ3YTNhZTM4MzkxNTUzMDk3NSJ9fX0="
    slot: 0
    name: "<aqua>Shop"
    lore:
      - "<gray>Click to open the shop"
  settings:
    enabled: true
    item:
    slot:
    name:
    lore: []
  join:
    enabled: true
    item:
    slot:
    name:
    lore: []
  island-selector:
    enabled: true
    item:
    slot:
    name:
    lore: []
  others: []

cosmetics:
  firework:
    enabled: true
    allowed-firework-models:
      BALL: 5000
      BURST: 5000
      STAR: 5000
      CREEPER: 5000
      BALL_LARGE: 5000
  material:
    default: "STONE"
    allowed-materials:
      STAINED_GLASS_PANE: 2600
      WOOL: 6500
      GOLD_BLOCK: 4500
