storage:
  type: MySQL
  host: localhost
  port: 3306
  ssl: false
  database: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASS}

cosmetics:
  firework:
    enabled: true
    allowed-firework-models:
      - "BALL"
      - "BURST"
      - "STAR"
      - "CREEPER"
      - "BALL_LARGE"