name: Bridger
version: '${project.version}'
main: io.github.alenalex.bridger.Bridger
authors: [ AlenAlex ]
description: A plugin for Bridging Practice
depend:
  - "Vault"
softdepend:
  - "PlaceholderAPI"
permissions: